#!/usr/bin/env python
import re

def translate(sequence):
    sequence = sequence.replace("R", "[AG]")
    sequence = sequence.replace("Y", "[CT]")
    sequence = sequence.replace("K", "[GT]")
    sequence = sequence.replace("M", "[AC]")
    sequence = sequence.replace("S", "[CG]")
    sequence = sequence.replace("W", "[AT]")
    sequence = sequence.replace("B", "[CGT]")
    sequence = sequence.replace("V", "[ACG]")
    sequence = sequence.replace("D", "[AGT]")
    sequence = sequence.replace("H", "[ACT]")
    return sequence

bible = open("sequence.fasta", "r")          #Replace with your FASTA file
lines = []
j = 0
for line in bible:
    lines.append(line.rstrip())
    j += 1
    print("Number of sequences pre-processed:", j)

sequence_str = "".join(lines)
pattern = translate("ARVTCA.ARKTCA")            #Replace with your query motif
res = [(m.group(), m.start()) for m in re.finditer(pattern, sequence_str)]

count = 0
for match in res:
    line_number = (match[1] // 72) + 1
    print(match[0], "found at line", line_number)
    count += 1

print("Total Matches:", count)
